### ISSUE TITLE
Sobre a nomeacao das classes

### ISSUE THREAD

**Issue by NicolasAoyama** [Monotremados-Grupo05/imobiliaria-spring#6]
Acho melhor a gente renomear algumas classes, as entitys estao todas em portugues, enquanto alguns controllers e algumas services estao em ingles. Isso pode gerar alguma duvida ou confusao no futuro.
As minhas que eu estou fazendo vou estar recriando pra deixar tudo em portugues.

**Comment by LucasQuadros19** [comment]
As q eu vou fazendo eu mudo pra pt, dai as q estão em ingles e pq nao 
esta prontas, mas vou mudando enquanto vai fazendo
